coverage:
  status:
    # Apply default rules for flags coverage not uploaded
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude

    # Set project-specific coverage targets
    project:
      array:
        target: auto
        threshold: 1%  # PR fails if coverage drops by 1% or more
      misc:
        target: auto
        threshold: 1%
      storage:
        target: auto
        threshold: 1%
      string:
        target: auto
        threshold: 1%
      uri:
        target: auto
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
