/* eslint-disable */
// devmoji.config.cjs — generated by holocron setup, do not edit
// https://github.com/folke/devmoji
const { defineConfig } = require("@theholocron/devmoji-config");
module.exports = defineConfig();
