sonar.projectKey=magnite:env-parser
sonar.projectName=Environment Parser
sonar.language=js

sonar.sources=src
sonar.exclusions=node_modules,**/__tests__/*,**/__mocks__/*,*.json
sonar.javascript.file.suffixes=.js

sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts*

sonar.testExecutionReportPaths=coverage/sonar.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.jstest.reportsPath=coverage/sonar.xml
sonar.coverage.exclusions=node_modules,**/__tests__/*,**/__mocks__/*,*.json
