name: Audit

# @TODO: add in more things like:
# - [ ] performance checks (using yellowpages, googles tools, etc)
# - [ ] dead css checks
# - [ ] coverage drops

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  bundle-size:
    name: Audit the bundle size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        name: Setup Node.js @v20
        with:
          cache: npm
          node-version: 20.x

      - run: npm ci
        name: Install dependencies

      - uses: jackyef/bundlewatch-gh-action@0.3.0
        name: Analyze using BundleWatch
        with:
          build-script: turbo run build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
