name: Dependencies

on: # yamllint disable-line rule:truthy
  - pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Update the dependencies
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - uses: dependabot/fetch-metadata@v2
        name: Fetch Dependabot metadata
        id: metadata

      - run: gh pr merge --auto --merge "$PR_URL"
        name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
